### ISSUE TITLE
Default basemap is https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png

### ISSUE THREAD

**Issue by starsep** [clarisma/geodesk-py#17]
According to https://docs.geodesk.com/python/Map#map-attributes
> Tile server URL for the base map (Default: OpenStreetMap Carto)

But actually
``` python
from geodesk import Map
print(Map().basemap)
```
> https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png

Please either change the default basemap or documentation.
I cannot find basemap in this repo so I suspect this line is responsible: https://github.com/clarisma/geodesk/blob/8d1aa56556920d47e42abd48a510cc167766e9b6/src/main/java/com/geodesk/util/MapMaker.java#L33

**Comment by clarisma** [comment]
Good catch, thanks! We'll change this in the next release.
In the meantime, you can set the basemap explicitly using:
- Python: `Map.basemap = "url"`
- Java: `MapMaker.tiles("url")`
- GOL Tool: `-f:basemap=url`

(Where *url* is this case is`https://tile.openstreetmap.org/{z}/{x}/{y}.png`)
