### ISSUE TITLE
Segmentation fault when iterating over empty feature set returned by `members_of`

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#18]
I've been trying out this library and I find it's very fast and easy to use!

However I've found that the following code causes a segmentation fault (contrived example to demonstrate the problem).

```
from geodesk import *
planet = Features("planet")
nodes = planet("n")
areas = planet("a")

for area in areas.members_of(nodes[0]):
    print(area)
```

Calling `areas.members_of(nodes[0]).count` or `first` or `list(...)` etc. also does the same.

**Comment by clarisma** [comment]
Thanks for catching this! A fix is on its way...
