### ISSUE TITLE
Area calculations way off near the poles

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#20]
I realise that [Core concepts](https://docs.geodesk.com/core-concepts) explains about the Mercator projection and I guess this is why the result of `.area` on objects near the poles overestimates their actual area.

It would be nice if (1) the documentation [here](https://docs.geodesk.com/python/Feature#Feature_area) mentioned this (if only to save GIS beginners some confusion why the numbers don't make sense), and (2) if the documentation pointed to a way to solve this in Python not just Java. (Ideally of course I’d like to get accurate area calculations from .area but I realise this may be out of scope.)

**Comment by clarisma** [comment]
Yes, it would make sense to re-project coordinates on the fly to make large area calculations more accurate near the poles. We'll put this into the next major release (Issue #22)

Related: Issue #1

**Comment by clarisma** [comment]
It turns out this is actually a bug (The Mercator projection, with a proper scale factor applied, actually returns reasonably accurate areas even near the poles). A fix is on its way.

**Comment by clarisma** [comment]
Caused by #32 (Fixed)
