### ISSUE TITLE
GeoJSON format wrong?

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#34]
It looks like Geodesk exports OSM ways that are areas with a `geometry` of `"type": "Polygon"` but gives the `"coordinates"` like you would give the coordinates for a `LineString`, with two levels of square brackets instead of three.

~~Similarly, multipolygons that are areas (single-member multipolygons) get exported with a `geometry` of `"type": "Polygon"` but the `"coordinates"` are given as if they were of type `MultiPolygon`, with four levels of square brackets instead of three.~~

This causes MapRoulette, and possibly other tools that consume GeoJSON, to fail.

**Comment by osmuser63783** [comment]
Sorry, have amended the first post. Multipolygons are handled fine. Single-member MPs get turned into "Polygon" with three levels of brackets ("array of arrays of positions"). Multi-member MPs get turned into "MultiPolygon" with four. The issue I was having with multipolygons was related to my own code.

Ways that are areas get turned into Polygon with two levels only ("array of positions"). This is against the GeoJSON spec.

Haven't tested ways that aren't areas.

Nodes seem to be fine.

**Comment by clarisma** [comment]
Thanks!
There is indeed a bug that causes incorrect GeoJSON for ways that are areas (The same bug affects WKT, but in reverse: polygons are fine, linestrings are wrong).
This is now fixed in `main` and will be released in 0.1.5.
