### ISSUE TITLE
Anonymous nodes don't return ways as parents (?)

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#43]
I think I've stumbled upon another bug.

```
highways = planet("w[highway]")
highways[0].nodes[0].parents.count
```

This gives 0. This can't be true, at least `highways[0]` should be a parent.

In fact a lot of anonymous nodes seem to return zero parents.
```
for i in highways[0].nodes:
    print(i.parents.count)
```

I've managed to find a node that reports it has a parent by doing:
```
for h in highways:
    for n in h.nodes:
        if n.parents.count != 0:
            print("Found one")
            print(n)
```

But that parent is a relation, not a way.

**Comment by clarisma** [comment]
Thanks, nice catch! Fix is coming...
