### ISSUE TITLE
Can't do intersects with anonymous nodes

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#44]
This works:
```
highways = planet("w[highway]")
restaurants = planet("n[amenity=restaurant]")
highways.intersects(restaurants[0])
```

This doesn't:
```
highways.intersects(highways[0].nodes[0])

TypeError: Expected geometric object instead of geodesk.AnonymousNode
```

NB: I create an issue when I find a bug or something unexpected (undocumented) happens. That doesn't mean I think this is a killer feature :-) In this case I only tried `intersects` because `parents` didn't work for the anonymous nodes.

**Comment by clarisma** [comment]
Thanks, all these reports are very helpful and much appreciated, even for seemingly minor issues.
