### ISSUE TITLE
Consecutive queries

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#45]
Why does
`planet('ar[boundary=administrative][admin_level=2][type!=multilinestring]').relations("*[name:en=Germany]")`
return four relations, some of which are not returned by
`planet('ar[boundary=administrative][admin_level=2][type!=multilinestring]').relations`
?

Only the following returns what I expected:
`planet('ar[boundary=administrative][admin_level=2][type!=multilinestring][name:en=Germany]').relations`

I would have expected these filters to work one after the other, so that adding another one can only ever make the resulting feature set smaller.

I would expect the following to work:
```
countries = planet('ar[boundary=administrative][admin_level=2][type!=multilinestring]').relations
countries('*[name:en=Germany]').one
```

Instead it complains: `QueryError: Expected only one feature, but found multiple.`

**Comment by clarisma** [comment]
Thanks for submitting this! 
Queries can now be combined; fix is in `main`, will release as part of 0.1.7.
