### ISSUE TITLE
Segfault when trying to access `.nodes` of relation

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#51]
... or at least that's what I think is going on.

```
traffic_sign_nodes_on_non_highways = set()
for h in planet_240219("aw[!highway]"):
    print(h)
    traffic_sign_nodes_on_non_highways.update(h.nodes("n[traffic_sign]"))
... 
way/120993860
way/120992621
way/120993742
way/986571987
way/120992739
way/120993191
relation/1655222
Segmentation fault (core dumped)
```

That's what I get for forgetting to do `.ways`.

It would be nice to fail more gracefully :-) (not sure if the method should return an empty set in case of an area, or all the nodes that define the multipolygon...)

**Comment by clarisma** [comment]
FYI -- your query `aw[!highway]` may also be effected by this bug: #52 ; fix coming soon

**Comment by clarisma** [comment]
Regarding `nodes` of relations, please see #54

**Comment by osmuser63783** [comment]
I have not been able to reproduce this recently so I am closing this issue. Sorry for the false positive!
