### ISSUE TITLE
Incorrect result for `Features.within`

### ISSUE THREAD

**Issue by osmuser63783** [clarisma/geodesk-py#57]
`Features.within` returns the following [island](https://www.openstreetmap.org/way/692587227) as lying entirely inside the [river area](https://www.openstreetmap.org/way/854475224), which is wrong.

<img width="459" alt="Screenshot 2024-04-28 at 17 37 12" src="https://github.com/clarisma/geodesk-py/assets/127188803/fb223097-8462-45e8-943d-a949c7bd89b8">
<img width="459" alt="Screenshot 2024-04-28 at 17 37 57" src="https://github.com/clarisma/geodesk-py/assets/127188803/9280b609-4ddb-455f-b2bb-f3f0e72255dd">

I think this is a bug in Geodesk.

Steps to reproduce:
```
my_water = next(w for w in planet_240422("a[natural=water]").ways if w.id == 854475224)
my_island = planet_240422("a[place=island,islet]").within(my_water).first # this line returns the island but shouldn't 
my_island.shape.within(my_water.shape) # Shapely returns false, which is the expected result
```

As a side note the definitions of `within` etc. can be a little counterintuitive: An island isn't "within" a lake if it shares a node with the lake, etc. If Geodesk follows the same definitions as Shapely, it could be helpful to link to [this](https://shapely.readthedocs.io/en/stable/manual.html#relationships) somewhere in the Geodesk docs.

**Comment by clarisma** [comment]
Thanks for opening this (the detailed screenshots are especially helpful).
Yes, this is clearly a bug.

On the definition of *within*, per OGC a shape is considered to be within itself (so A can share nodes with B and still be considered *within* B). This is the definition used by GEOS (and hence Shapely). But in your example, the island lies outside the river area (all its nodes lie inside the river area, which appears to trigger the false positive).
